server:
  port: 8088

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=192.141.44.250)(PORT=1521)))(LOAD_BALANCE=yes)(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=bjrd)))
    username: npcbj
    password: npcbj_bcc_ac_cn*$
  redis:
    database: 0
    host: 192.141.44.34
    port: 6379

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
