create table QUERY_STATEMENT
(
  id          NUMBER(9) not null,
  name        VARCHAR2(50),
  statement   VARCHAR2(2000),
  description VARCHAR2(50)
)
tablespace NPCBJ_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 8K
    minextents 1
    maxextents unlimited
  );
alter table QUERY_STATEMENT
  add constraint ID primary key (ID)
  using index
  tablespace NPCBJ_TABLESPACE
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );

insert into QUERY_STATEMENT (id, name, statement, description)
values (1, 'PROPOSAL_SUM', 'SELECT  count(*) AS count,  ''本届提交总数'' AS x0 FROM  BCC_PROPOSAL where  sessions=(select value from BCC_CONFIG where key = ''dpSessions'')' || chr(10) || 'union select count(*) AS count,  ''参与主提'' AS x0 from(SELECT  count(PROPOSER_ID) FROM  BCC_PROPOSAL where  sessions=(select value from BCC_CONFIG where key = ''dpSessions'') group by PROPOSER_ID)' || chr(10) || 'union SELECT  count(*) AS count,  ''附议数量''  from BCC_SECONDED t where proposal_id in (SELECT proposal_id FROM  BCC_PROPOSAL where  sessions=(select value from BCC_CONFIG where key = ''dpSessions'')) ' || chr(10) || 'union select count(*)  AS count,  ''参与附议'' AS x0 from (select count(user_id) from BCC_SECONDED t where proposal_id in (SELECT proposal_id FROM  BCC_PROPOSAL where  sessions=(select value from BCC_CONFIG where key = ''dpSessions'')) group by user_id)' || chr(10) || 'union SELECT  count(*) AS count,  ''待定'' AS x0 FROM  BCC_PROPOSAL where  sessions=(select value from BCC_CONFIG where key = ''dpSessions'') and INSTEAD_PROPOSER_ID is not null' || chr(10) || 'union SELECT  count(*) AS count,  ''待定'' AS x0 FROM  BCC_PROPOSAL where  sessions=(select value from BCC_CONFIG where key = ''dpSessions'') and INSTEAD_PROPOSER_ID is null', '数量统计-提交总数-未');
insert into QUERY_STATEMENT (id, name, statement, description)
values (2, 'SUBMIT_SUM', 'SELECT' || chr(10) || '  count(*) count,' || chr(10) || '  ''上届自提''  x0' || chr(10) || 'FROM' || chr(10) || '  bcc_proposal_view' || chr(10) || 'WHERE' || chr(10) || '  sessions = (select value from BCC_CONFIG where key = ''dpSessions'')-1' || chr(10) || 'and ' || chr(10) || '  is_proposal=1' || chr(10) || 'and INSTEAD_PROPOSER_ID is  null' || chr(10) || '' || chr(10) || 'union all' || chr(10) || '' || chr(10) || 'SELECT' || chr(10) || '  count(*) count,' || chr(10) || '  ''上届代提''  x0' || chr(10) || 'FROM' || chr(10) || '  bcc_proposal_view' || chr(10) || 'WHERE' || chr(10) || '  sessions = (select value from BCC_CONFIG where key = ''dpSessions'')-1' || chr(10) || 'and ' || chr(10) || '  is_proposal=1' || chr(10) || 'and INSTEAD_PROPOSER_ID is not null' || chr(10) || '' || chr(10) || 'union all' || chr(10) || '' || chr(10) || 'SELECT' || chr(10) || '  count(*) count,' || chr(10) || '  ''本届自提''  x0' || chr(10) || 'FROM' || chr(10) || '  bcc_proposal_view' || chr(10) || 'WHERE' || chr(10) || '  sessions = (select value from BCC_CONFIG where key = ''dpSessions'')' || chr(10) || 'and ' || chr(10) || '  is_proposal=1' || chr(10) || 'and INSTEAD_PROPOSER_ID is  null' || chr(10) || '' || chr(10) || 'union all' || chr(10) || '' || chr(10) || 'SELECT' || chr(10) || '  count(*) count,' || chr(10) || '  ''本届代提''  x0' || chr(10) || 'FROM' || chr(10) || '  bcc_proposal_view' || chr(10) || 'WHERE' || chr(10) || '  sessions = (select value from BCC_CONFIG where key = ''dpSessions'')' || chr(10) || 'and ' || chr(10) || '  is_proposal=1' || chr(10) || 'and INSTEAD_PROPOSER_ID is not null', '提出类型-百分比');
insert into QUERY_STATEMENT (id, name, statement, description)
values (3, 'UNIT_HANDLE_SUM', 'select * from ' || chr(10) || '(' || chr(10) || 'SELECT' || chr(10) || '  count(u.username) COUNT,' || chr(10) || '  u.username X0' || chr(10) || 'FROM' || chr(10) || '  BCC_PROPOSAL_confirm h' || chr(10) || 'left join ' || chr(10) || '  bcc_user u' || chr(10) || 'on h.handle_unit_id=u.id' || chr(10) || 'WHERE' || chr(10) || '  h.proposal_id in (SELECT proposal_id FROM   BCC_PROPOSAL WHERE   sessions = (select value from BCC_CONFIG where key = ''dpSessions'')  )' || chr(10) || '  and h.handle_way in (1,2)' || chr(10) || 'group by u.username' || chr(10) || 'order by COUNT desc' || chr(10) || ') a' || chr(10) || 'where rownum<=20', '承办单位-排行榜');
insert into QUERY_STATEMENT (id, name, statement, description)
values (4, 'SYSTEM_SUM', 'SELECT' || chr(10) || '  count(g.name) COUNT,' || chr(10) || '  g.name X0' || chr(10) || 'FROM' || chr(10) || '  BCC_PROPOSAL_VIEW p' || chr(10) || 'left join ' || chr(10) || '  bcc_group g' || chr(10) || '  on p.system_group_id=g.id' || chr(10) || 'WHERE' || chr(10) || '   p.sessions=(select value from BCC_CONFIG where key = ''dpSessions'')' || chr(10) || 'and g.name is not null' || chr(10) || 'group by g.name' || chr(10) || '' || chr(10) || '', '系统-分配排名');
insert into QUERY_STATEMENT (id, name, statement, description)
values (5, 'SUBJECT_SUM', 'select ' || chr(10) || 'count(*) COUNT,' || chr(10) || 'first_subject_word_name x0' || chr(10) || 'from BCC_PROPOSAL_view ' || chr(10) || 'where sessions=(select value from BCC_CONFIG where key = ''dpSessions'')' || chr(10) || '  AND first_subject_word_name IS NOT NULL' || chr(10) || 'group by first_subject_word_name' || chr(10) || 'union ' || chr(10) || 'select ' || chr(10) || '  0 COUNT,' || chr(10) || '  Name x0' || chr(10) || 'from Bcc_Subject_Words' || chr(10) || ' ', '一级主题词');
insert into QUERY_STATEMENT (id, name, statement, description)
values (6, 'GROUP_SUM', 'select count(*) as COUNT,group_name  as X0' || chr(10) || 'from BCC_PROPOSAL_VIEW t ' || chr(10) || 'where sessions=(select value from BCC_CONFIG where key = ''dpSessions'')' || chr(10) || 'and is_meeting =1' || chr(10) || 'and state>=21' || chr(10) || 'group by group_name', '代表团');
insert into QUERY_STATEMENT (id, name, statement, description)
values (7, 'PROPOSAL_LEFT_SUM', 'SELECT ' || chr(10) || '  ''代表团未提交数'' x0,' || chr(10) || '  nvl(COUNT(*), 0) count ' || chr(10) || 'FROM' || chr(10) || '  bcc_proposal o' || chr(10) || 'WHERE ' || chr(10) || '  o.sessions in ((select value from BCC_CONFIG where key = ''dpSessions''))' || chr(10) || '  and o.is_meeting=1' || chr(10) || 'and state = 21' || chr(10) || '' || chr(10) || 'union all' || chr(10) || '' || chr(10) || 'SELECT ' || chr(10) || '  ''建议已提交总数'' x0,' || chr(10) || '  nvl(COUNT(*), 0) count ' || chr(10) || 'FROM' || chr(10) || '  bcc_proposal_view o' || chr(10) || 'WHERE ' || chr(10) || '  o.sessions in ((select value from BCC_CONFIG where key = ''dpSessions''))' || chr(10) || '  and o.is_meeting=1' || chr(10) || 'and is_proposal=1' || chr(10) || '' || chr(10) || 'union all' || chr(10) || '' || chr(10) || 'SELECT ' || chr(10) || '  ''建议未确认数'' x0,' || chr(10) || '  nvl(COUNT(*), 0) count ' || chr(10) || 'FROM' || chr(10) || '  bcc_proposal o' || chr(10) || 'WHERE ' || chr(10) || '  o.sessions in ((select value from BCC_CONFIG where key = ''dpSessions''))' || chr(10) || '  and o.is_meeting=1' || chr(10) || 'and o.state>31 and o.state<=61' || chr(10) || '' || chr(10) || 'union all' || chr(10) || '' || chr(10) || 'SELECT ' || chr(10) || '  ''参与主提代表数'' x0,' || chr(10) || '  count(*) count ' || chr(10) || '  from ' || chr(10) || '(select DISTINCT  proposer_id FROM  bcc_proposal o' || chr(10) || 'WHERE ' || chr(10) || '  o.sessions in ((select value from BCC_CONFIG where key = ''dpSessions''))' || chr(10) || '  and o.is_meeting=1' || chr(10) || 'group by proposer_id' || chr(10) || ') t', '提-审-分情况');
insert into QUERY_STATEMENT (id, name, statement, description)
values (8, 'STATE_SUM',
        'select * from ' || chr(10) || '(select ' || chr(10) || '''全部'' as X0,' || chr(10) || 'count(*) as COUNT ' || chr(10) || 'from BCC_PROPOSAL_VIEW t' || chr(10) || 'where t.sessions=(select value from BCC_CONFIG where key = ''dpSessions'')' || chr(10) || 'and t.is_meeting=1' || chr(10) || ') a' || chr(10) || 'union all' || chr(10) || '' || chr(10) || 'select * from ' || chr(10) || '(select ' || chr(10) || 'case t.state' || chr(10) || '   when 0 then ''不作为建议''' || chr(10) || '   when 11  then ''留言中''' || chr(10) || '   when 12  then ''附议中''' || chr(10) || '   when 13  then ''结束征集留言''' || chr(10) || '   when 14  then ''结束征集附议''' || chr(10) || '   when 15  then ''代表团不通过''' || chr(10) || '   when 21  then ''代表团待审核''' || chr(10) || '   when 22  then ''建议组直接退回''' || chr(10) || '   when 23  then ''代表申请撤回''' || chr(10) || '   when 31  then ''待分配''' || chr(10) || '   when 32  then ''建议组已分配''' || chr(10) || '   when 33  then ''组员退回''' || chr(10) || '   when 34  then ''待交系统''' || chr(10) || '   when 35  then ''一府两院退回''' || chr(10) || '   when 36  then ''代表团通过代表撤回''' || chr(10) || '   when 37  then ''大会建议组通过代表撤回''' || chr(10) || '   when 40  then ''承办单位的退件''' || chr(10) || '   when 41  then ''分配系统单位''' || chr(10) || '   when 42  then ''分配至业务组''' || chr(10) || '   when 43  then ''分配至组员''' || chr(10) || '   when 44  then ''再分配至组员''' || chr(10) || '   when 45  then ''组员退回给业务组''' || chr(10) || '   when 46  then ''业务组退回系统单位''' || chr(10) || '   when 47  then ''建议组再分配系统单位''' || chr(10) || '   when 48  then ''承办单位退回至系统单位''' || chr(10) || '   when 49  then ''业务组组员待处理''' || chr(10) || '   when 51  then ''预交办承办单位''' || chr(10) || '   when 61  then ''待正式交办''' || chr(10) || '   when 62  then ''确定公开 ''' || chr(10) || '   when 71  then ''承办单位办理中''' || chr(10) || '   when 81  then ''已办结''' || chr(10) || '   when 91  then ''已反馈''' || chr(10) || '   when 92  then ''待复查''' || chr(10) || '   when 93  then ''复查中''' || chr(10) || '   when 94  then ''待确定重办''' || chr(10) || '   when 95  then ''重新办理中''' || chr(10) || '   when 96  then ''已重办''' || chr(10) || '       else ''其他''' || chr(10) || '    end' || chr(10) || 'as X0,' || chr(10) || 'count(*) as COUNT ' || chr(10) || '' || chr(10) || 'from BCC_PROPOSAL_VIEW t' || chr(10) || 'where t.sessions=(select value from BCC_CONFIG where key = ''dpSessions'')' || chr(10) || 'and t.is_meeting=1' || chr(10) || 'group by t.state' || chr(10) || 'order by t.state' || chr(10) || ')' || chr(10) || 'b',
        '建议状态统计');
insert into QUERY_STATEMENT (id, name, statement, description)
values (9, 'LOGIN_LOG', 'select * from (' || chr(10) || '' || chr(10) || 'select * from (select accountname as name,to_char(logintime,''hh:mm:ss'') as time, message ' || chr(10) || 'from BCC_USERLOGIN t ' || chr(10) || 'where rownum < 50 ' || chr(10) || 'and accountname not like ''admin%''  ' || chr(10) || 'and accountname not like ''建议综合组组长%''  ' || chr(10) || 'and message not like ''用户名或密码不正确''  ' || chr(10) || 'order by logintime desc ) a' || chr(10) || '' || chr(10) || 'union all' || chr(10) || 'select * from' || chr(10) || '(select ' || chr(10) || '      u.username as name,' || chr(10) || '      to_char(t.operate_time,''hh:mm:ss'') as time, ' || chr(10) || '      case t.stage' || chr(10) || '          when 1 then ''提交''' || chr(10) || '          when 2 then ''审核''' || chr(10) || '          when 3 then ''审核''' || chr(10) || '          when 4 then ''交办''' || chr(10) || '          when 5 then ''办理''' || chr(10) || '      end as message' || chr(10) || 'from bcc_proposal_history t ' || chr(10) || 'left join bcc_user u on t.operator_id=u.id' || chr(10) || 'where rownum < 50  ' || chr(10) || 'order by t.operate_time desc ) b' || chr(10) || ') c order by time', '登录日志');
insert into QUERY_STATEMENT (id, name, statement, description)
values (10, 'GROUP_HAN_SUM', 'select a.COUNT as ALL_COUNT,' || chr(10) || 'b.COUNT as HAN_COUNT,' || chr(10) || 'a.X0  as X0' || chr(10) || 'from ' || chr(10) || '(select count(*) as COUNT,group_name  as X0' || chr(10) || 'from BCC_PROPOSAL_VIEW t ' || chr(10) || 'where sessions=(select value from BCC_CONFIG where key = ''dpSessions'')' || chr(10) || 'and is_meeting =1' || chr(10) || 'and state>=21' || chr(10) || 'group by group_name) a' || chr(10) || ',' || chr(10) || '(select count(*) as COUNT,group_name  as X0' || chr(10) || 'from BCC_PROPOSAL_VIEW t ' || chr(10) || 'where sessions=(select value from BCC_CONFIG where key = ''dpSessions'')' || chr(10) || 'and is_meeting =1' || chr(10) || 'and state>=61' || chr(10) || 'group by group_name) b' || chr(10) || '' || chr(10) || 'where a.X0=b.X0' || chr(10) || '', '代表团提出-分配比例');
insert into QUERY_STATEMENT (id, name, statement, description)
values (11, 'PREV_SESSION_ME', 'select CONCAT(TRUNC(((a.count-b.count)/b.count)*100,2),''%'') as count,' || chr(10) || ' ''自提同比上届'' x0' || chr(10) || ' from ' || chr(10) || '(' || chr(10) || 'SELECT' || chr(10) || '  count(*) count' || chr(10) || 'FROM' || chr(10) || '  bcc_proposal_view' || chr(10) || 'WHERE' || chr(10) || '  sessions = (select value from BCC_CONFIG where key = ''dpSessions'')' || chr(10) || 'and ' || chr(10) || '  is_proposal=1' || chr(10) || 'and INSTEAD_PROPOSER_ID is  null' || chr(10) || ') a' || chr(10) || ',(' || chr(10) || 'SELECT' || chr(10) || '  count(*) count' || chr(10) || 'FROM' || chr(10) || '  bcc_proposal_view' || chr(10) || 'WHERE' || chr(10) || '  sessions = (select value from BCC_CONFIG where key = ''dpSessions'')-1' || chr(10) || 'and ' || chr(10) || '  is_proposal=1' || chr(10) || 'and INSTEAD_PROPOSER_ID is  null' || chr(10) || ') b' || chr(10) || '' || chr(10) || 'union all' || chr(10) || '' || chr(10) || 'select CONCAT(TRUNC(((a.count-b.count)/b.count)*100,2),''%'') as count,' || chr(10) || ' ''代提同比上届'' x0' || chr(10) || ' from ' || chr(10) || '(' || chr(10) || 'SELECT' || chr(10) || '  count(*) count' || chr(10) || 'FROM' || chr(10) || '  bcc_proposal_view' || chr(10) || 'WHERE' || chr(10) || '  sessions = (select value from BCC_CONFIG where key = ''dpSessions'')' || chr(10) || 'and ' || chr(10) || '  is_proposal=1' || chr(10) || 'and ' || chr(10) || '  INSTEAD_PROPOSER_ID is not null' || chr(10) || ') a' || chr(10) || ',(' || chr(10) || 'SELECT' || chr(10) || '  count(*) count' || chr(10) || 'FROM' || chr(10) || '  bcc_proposal_view' || chr(10) || 'WHERE' || chr(10) || '  sessions = (select value from BCC_CONFIG where key = ''dpSessions'')-1' || chr(10) || 'and ' || chr(10) || '  is_proposal=1' || chr(10) || 'and ' || chr(10) || '  INSTEAD_PROPOSER_ID is not null' || chr(10) || ') b', '自提\代提同比上届');